config/routes.rb
Rails.application.routes.draw do
  # 会員用deviseのルーティング（/members/sign_in）
  devise_for :members, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  # 管理者用deviseのルーティング（/admin/sign_in）
  devise_for :admin, skip: %i[passwords registrations], controllers: {
    sessions: 'admin/sessions'
  }

  # 管理者用ルーティング
  namespace :admin do
    get '/top' => 'homes#top'
    get 'about' => 'homes#about'

    resources :hotels do
      resources :reviews, except: %i[new create] do # ホテル：レビュー = １：Nだからネスト
        resources :review_comments, only: %i[update destroy] # レビュー：コメント = １：Nだからネスト
      end
    end

    resources :categories, only: %i[index create edit update destroy show]
    resources :areas, only: %i[index create edit update destroy show]
    resources :pictures, only: %i[index new create destroy]

    # 検索機能
    get '/hotel_search' => 'searches#hotel_search'

    # 会員のusernameがURLに表示される
    get '/members' => 'members#index'
    get '/:username' => 'members#show'
    get '/:username/edit' => 'members#edit'
    patch '/:username' => 'members#update'
    patch '/:username/withdraw' => 'members#withdraw', as: 'withdraw_member'
  end

  # 会員側ルーティング
  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get '/privacy' => 'homes#privacy'

    resources :hotels, only: %i[index show] do
      collection do
        get 'ranking'
      end

      resources :reviews do # ホテル：レビュー = １：Nだからネスト
        resources :review_comments, only: %i[create update destroy] # レビュー：コメント = １：Nだからネスト
      end

      resource :favorites, only: %i[create destroy] # ホテル：お気に入り = １：Nだからネスト
    end

    # 検索機能
    get '/hotel_search' => 'searches#hotel_search'

    resources :pictures, only: [:index]

    # お問い合わせ機能
    resources :contacts, only: %i[new create] do
      collection do
        post 'confirm'
        post 'back'
        get 'complete'
      end
    end

    resources :areas, only: [:show]
    resources :categories, only: [:show]

    # URLがusernameになるようにルーティング設定
    get '/mypage' => 'members#mypage', as: "mypage"
    get '/:username' => 'members#show'
    get '/mypage/edit' => 'members#edit', as: "edit_mypage"
    get '/mypage/favorites' => 'members#favorites', as: "favorite_mypage"
    patch '/mypage' => 'members#update', as: "update_mypage"
    get '/mypage/unsubscribe' => 'members#unsubscribe', as: "unsubscribe_member"
    patch '/mypge/withdraw' => 'members#withdraw', as: 'withdraw_member'
  end
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  # 住所から緯度経度取得
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :hotel_images, dependent: :destroy
  accepts_attachments_for :hotel_images, attachment: :image # refileで画像複数枚アップロード
  belongs_to :category
  belongs_to :area

  validates :category_id, presence: true
  validates :area_id, presence: true
  validates :hotel_name, presence: true
  validates :price_range, presence: true
  validates :caption, presence: true
  validates :website, presence: true
  validates :address, presence: true
  validates :hotel_images, presence: true

  # 評価の平均点
  def avg_rate
    if reviews.includes(:reviews).empty?
      0.0
    else
      reviews.average(:rate).round(1)
    end
  end

  # ホテル名から検索
  def self.search(search)
    if search
      Hotel.where('hotel_name LIKE(?)', "%#{search}%")
    else
      Hotel.all
    end
  end
end

app/controllers/admin/hotels_controller.rb
class Admin::HotelsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @hotels = Hotel.includes(:category, :area).page(params[:page]).per(12)
    # binding.pry
    @categories = Category.all
    @areas = Area.all
    gon.hotels = Hotel.all
  end

  def new
    @hotel = Hotel.new
    @hotel.hotel_images.build
    @categories = Category.all
    @areas = Area.all
  end

  def create
    @hotel = Hotel.new(hotel_params)
    if @hotel.save
      flash[:notice] = 'ホテル情報を登録しました。'
      redirect_to admin_hotel_path(@hotel)
    else
      flash.now[:alert] = 'ホテル情報を登録できませんでした。'
      render :new
    end
  end

  def show
    @hotel = Hotel.find(params[:id])
    gon.hotel = Hotel.find(params[:id])
  end

  def edit
    @hotel = Hotel.find(params[:id])
    @hotel.hotel_images.all
    @categories = Category.all
    @areas = Area.all
  end

  def update
    @hotel = Hotel.find(params[:id])
    if @hotel.update(hotel_params)
      flash[:notice] = 'ホテル情報を更新しました。'
      redirect_to admin_hotel_path(@hotel)
    else
      flash.now[:alert] = 'ホテル情報を更新できませんでした。再度入力してください。'
      render :edit
    end
  end

  private

  def hotel_params
    params.require(:hotel).permit(:category_id, :area_id, :hotel_name, :price_range, :website, :caption, :address,
                                  :latitude, :longitude, hotel_images_images: [])
  end
end

app/helpers/admin/hotels_helper.rb
module Admin::HotelsHelper
end

app/views/admin/hotels/_area_search.html.erb
<div class="border border-info p-1 text-center">
  <h6>エリア検索</h6>
</div>

<div class="border border-info p-3">
  <ul class="list-unstyled">
    <% areas.each do |area| %>
      <%= link_to admin_area_path(area) do %>
        <li style="font-size: 12px"><%= area.area_name %></li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/admin/hotels/_category_search.html.erb
<div class="border border-info p-1 text-center">
  <h6>ジャンル検索</h6>
</div>

<div class="border border-info p-3">
  <ul class="list-unstyled">
    <% categories.each do |category| %>
    <li style="font-size: 12px">
      <%= link_to admin_category_path(category) do %>
        <%= category.category_name %>
      <% end %>
    </li>
    <% end %>
  </ul>
</div>

app/views/admin/hotels/edit.html.erb
<div class="container-fluid">
  <div class="row justify-content-center mb-3">
    <h3 style="border-bottom: 2px solid #FF9933">ホテル情報編集</h3>
  </div>

  <%= form_with model: @hotel, url: admin_hotel_path, local: true do |f| %>
  <div class="row">
    <%= f.label :"ホテル画像(複数可)", class: "col-10 offset-1 col-md-2 offset-md-3 font-weight-bold" %>
    <%= f.attachment_field :hotel_images_images, multiple: true, class: "col-10 offset-2 col-md-5 offset-md-0" %>
  </div>
  <div class="row mt-2">
    <%= f.label :"ホテル名", class: "col-10 offset-1 col-md-2 offset-md-3 font-weight-bold" %>
    <%= f.text_field :hotel_name, autocomplete: true, class: "col-8 offset-2 col-md-5 offset-md-0 form-control" %>
    <% if @hotel.errors.include?(:hotel_name) %>
      <div class="col-10 offset-2 col-md-5 offset-md-3" style="color: red;"><%= @hotel.errors.full_messages_for(:hotel_name).first %></div>
    <% end %>
  </div>
  <div class="row mt-2">
    <%= f.label :"ホームページ", class: "col-10 offset-1 col-md-2 offset-md-3 font-weight-bold" %>
    <%= f.text_field :website, autocomplete: true, class: "col-8 offset-2 col-md-5 offset-md-0 form-control" %>
    <% if @hotel.errors.include?(:website) %>
      <div class="col-10 offset-2 col-md-5 offset-md-3" style="color: red;"><%= @hotel.errors.full_messages_for(:website).first %></div>
    <% end %>
  </div>
  <div class="row mt-2">
    <%= f.label :"カテゴリ", class: "col-10 offset-1 col-md-2 offset-md-3 font-weight-bold" %>
    <%= f.collection_select :category_id, Category.all, :id, :category_name, {prompt: "選択してください"}, {class: "col-8 offset-2 col-md-5 offset-md-0 form-control"} %>
    <% if @hotel.errors.include?(:category_id) %>
      <div class="col-10 offset-2 col-md-5 offset-md-3" style="color: red;"><%= @hotel.errors.full_messages_for(:category_id).first %></div>
    <% end %>
  </div>
  <div class="row mt-2">
    <%= f.label :"エリア", class: "col-10 offset-1 col-md-2 offset-md-3 font-weight-bold" %>
    <%= f.collection_select :area_id, Area.all, :id, :area_name, {prompt: "選択してください"}, {class: "col-8 offset-2 col-md-5 offset-md-0 form-control"} %>
    <% if @hotel.errors.include?(:area_id) %>
      <div class="col-10 offset-2 col-md-5 offset-md-3" style="color: red;"><%= @hotel.errors.full_messages_for(:area_id).first %></div>
    <% end %>
  </div>
  <div class="row mt-2">
    <%= f.label :"価格帯", class: "col-10 offset-1 col-md-2 offset-md-3 font-weight-bold" %>
    <%= f.text_field :price_range, autocomplete: true, class: "col-8 offset-2 col-md-5 offset-md-0 form-control" %>
    <% if @hotel.errors.include?(:price_range) %>
      <div class="col-10 offset-2 col-md-5 offset-md-3" style="color: red;"><%= @hotel.errors.full_messages_for(:price_range).first %></div>
    <% end %>
  </div>
  <div class="row mt-2">
    <%= f.label :"特徴", class: "col-10 offset-1 col-md-2 offset-md-3 font-weight-bold" %>
    <%= f.text_area :caption, autocomplete: true, class: "col-8 offset-2 col-md-5 offset-md-0 form-control" %>
    <% if @hotel.errors.include?(:caption) %>
      <div class="col-10 offset-2 col-md-5 offset-md-3" style="color: red;"><%= @hotel.errors.full_messages_for(:caption).first %></div>
    <% end %>
  </div>
  <div class="row mt-2">
    <%= f.label :"住所", class: "col-10 offset-1 col-md-2 offset-md-3 font-weight-bold" %>
    <%= f.text_field :address, autocomplete: true, class: "col-8 offset-2 col-md-5 offset-md-0 form-control" %>
    <% if @hotel.errors.include?(:address) %>
      <div class="col-10 offset-2 col-md-5 offset-md-3" style="color: red;"><%= @hotel.errors.full_messages_for(:address).first %></div>
    <% end %>
  </div>
  <div class="row justify-content-center">
    <%= f.submit "更新", class: "col-6 col-md-2 btn btn-success my-3" %>
  </div>
  <% end %>

</div>

app/views/admin/hotels/index.html.erb
<div class="container-fluid">

  <div class="row justify-content-center mb-3">
    <h3 style="border-bottom: 2px solid #FF9933">浦安市のホテル一覧</h3>
  </div>

  <div class="row justify-content-center">

    <div class="order-2 order-md-1 col-md-4 col-lg-3 d-flex flex-column">
      <div>
        <%= render "admin/hotels/category_search", categories: @categories %>
      </div>
      <div class="mt-3">
        <%= render "admin/hotels/area_search", areas: @areas %>
      </div>
      <div class="my-3" id="admin-map-index"></div>
        <script async defer src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV["GOOGLE_MAP_API_KEY"] %>&callback=admin_map_index"></script>
    </div>

    <div class="order-1 order-md-2 col-md-8 col-lg-9">
      <div class="text-center text-md-right mr-md-5 mb-2">
        <%= link_to "ホテルを登録する", new_admin_hotel_path, class: "btn btn-info" %>
      </div>
      <div class="d-flex flex-wrap justify-content-center justify-content-md-start">
        <% @hotels.each do |hotel| %>
        <div class="d-flex flex-column mb-3 mr-md-2 mr-lg-3">
          <div>
            <%= link_to admin_hotel_path(hotel) do %>
              <% hotel.hotel_images.first(1).each do |image| %>
                <%= attachment_image_tag image, :image, :fill, 225, 200 %>
              <% end %>
            <% end %>
          </div>
          <div style="font-size: 13px; width:225px"><strong><%= hotel.hotel_name %></strong></div>
          <div style="font-size: 11px; width:225px">カテゴリ：<%= hotel.category.category_name %></div>
          <div style="font-size: 11px; width:225px">エリア：<%= hotel.area.area_name %></div>
          <div style="font-size: 11px">評価：<%= hotel.avg_rate %> 点（5点満点）</div>
        </div>
        <% end %>
      </div>
      <div class="d-flex justify-content-center mt-2"><%= paginate @hotels %></div>
    </div>

  </div>

</div>

app/views/admin/hotels/new.html.erb
<div class="container-fluid">
  <div class="row justify-content-center mb-3">
    <h3 style="border-bottom: 2px solid #FF9933">ホテル情報登録</h3>
  </div>

  <%= form_with model: @hotel, url: admin_hotels_path, local: true do |f| %>
  <div class="row">
    <%= f.label :"ホテル画像(複数可)", class: "col-10 offset-1 col-md-2 offset-md-3 font-weight-bold" %>
    <%= f.attachment_field :hotel_images_images, multiple: true, class: "col-10 offset-2 col-md-5 offset-md-0" %>
    <% if @hotel.errors.include?(:hotel_images) %>
      <div class="col-10 offset-2 col-md-5 offset-md-3" style="color: red;"><%= @hotel.errors.full_messages_for(:hotel_images).first %></div>
    <% end %>
  </div>
  <div class="row mt-2">
    <%= f.label :"ホテル名", class: "col-10 offset-1 col-md-2 offset-md-3 font-weight-bold" %>
    <%= f.text_field :hotel_name, autocomplete: true, class: "col-8 offset-2 col-md-5 offset-md-0 form-control" %>
    <% if @hotel.errors.include?(:hotel_name) %>
      <div class="col-10 offset-2 col-md-5 offset-md-3" style="color: red;"><%= @hotel.errors.full_messages_for(:hotel_name).first %></div>
    <% end %>
  </div>
  <div class="row mt-2">
    <%= f.label :"ホームページ", class: "col-10 offset-1 col-md-2 offset-md-3 font-weight-bold" %>
    <%= f.text_field :website, autocomplete: true, class: "col-8 offset-2 col-md-5 offset-md-0 form-control" %>
    <% if @hotel.errors.include?(:website) %>
      <div class="col-10 offset-2 col-md-5 offset-md-3 text-nowrap" style="color: red;"><%= @hotel.errors.full_messages_for(:website).first %></div>
    <% end %>
  </div>
  <div class="row mt-2">
    <%= f.label :"カテゴリ", class: "col-10 offset-1 col-md-2 offset-md-3 font-weight-bold" %>
    <%= f.collection_select :category_id, Category.all, :id, :category_name, {prompt: "選択してください"}, {class: "col-8 offset-2 col-md-5 offset-md-0 form-control"} %>
    <% if @hotel.errors.include?(:category_id) %>
      <div class="col-10 offset-2 col-md-5 offset-md-3" style="color: red;"><%= @hotel.errors.full_messages_for(:category_id).first %></div>
    <% end %>
  </div>
  <div class="row mt-2">
    <%= f.label :"エリア", class: "col-10 offset-1 col-md-2 offset-md-3 font-weight-bold" %>
    <%= f.collection_select :area_id, Area.all, :id, :area_name, {prompt: "選択してください"}, {class: "col-8 offset-2 col-md-5 offset-md-0 form-control"} %>
    <% if @hotel.errors.include?(:area_id) %>
      <div class="col-10 offset-2 col-md-5 offset-md-3" style="color: red;"><%= @hotel.errors.full_messages_for(:area_id).first %></div>
    <% end %>
  </div>
  <div class="row mt-2">
    <%= f.label :"価格帯", class: "col-10 offset-1 col-md-2 offset-md-3 font-weight-bold" %>
    <%= f.text_field :price_range, autocomplete: true, class: "col-8 offset-2 col-md-5 offset-md-0 form-control" %>
    <% if @hotel.errors.include?(:price_range) %>
      <div class="col-10 offset-2 col-md-5 offset-md-3" style="color: red;"><%= @hotel.errors.full_messages_for(:price_range).first %></div>
    <% end %>
  </div>
  <div class="row mt-2">
    <%= f.label :"特徴", class: "col-10 offset-1 col-md-2 offset-md-3 font-weight-bold" %>
    <%= f.text_area :caption, autocomplete: true, class: "col-8 offset-2 col-md-5 offset-md-0 form-control" %>
    <% if @hotel.errors.include?(:caption) %>
      <div class="col-10 offset-2 col-md-5 offset-md-3" style="color: red;"><%= @hotel.errors.full_messages_for(:caption).first %></div>
    <% end %>
  </div>
  <div class="row mt-2">
    <%= f.label :"住所", class: "col-10 offset-1 col-md-2 offset-md-3 font-weight-bold" %>
    <%= f.text_field :address, autocomplete: true, class: "col-8 offset-2 col-md-5 offset-md-0 form-control" %>
    <% if @hotel.errors.include?(:address) %>
      <div class="col-10 offset-2 col-md-5 offset-md-3" style="color: red;"><%= @hotel.errors.full_messages_for(:address).first %></div>
    <% end %>
  </div>
  <div class="row justify-content-center">
    <%= f.submit "登録", class: "col-6 col-md-2 btn btn-success my-3" %>
  </div>
  <% end %>

</div>

app/views/admin/hotels/show.html.erb
<div class="container-fluid">

  <div class="row justify-content-center">
    <h3 class="head-text" style="border-bottom: 2px solid #FF9933"><%= @hotel.hotel_name %></h3>
  </div>

  <div class="row mt-3 justify-content-center">
    <div class="col-12 col-md-8">
      <div class="slider">
      <% @hotel.hotel_images.each do |image| %>
        <%= attachment_image_tag image, :image, class: "img-show img-fluid" %>
      <% end %>
      </div>
      <p class="caption text-break"><%= @hotel.caption %></p>
    </div>
  </div>

  <div class="row justify-content-center mt-3">
    <div class="col-10 col-md-4 offset-md-1 mb-3" id="map"></div>
      <script async defer src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV["GOOGLE_MAP_API_KEY"] %>&callback=initMap"></script>
    <div class="col-md-6">
      <table class="table table-bordered">
        <tr>
          <th width="35%">ホームページ</th>
          <td width="65%" class="text-break"><%= text_url_to_link(h(@hotel.website)).html_safe %></td>
        </tr>
        <tr>
          <th>カテゴリ</th>
          <td><%= @hotel.category.category_name %></td>
        </tr>
        <tr>
          <th>エリア</th>
          <td><%= @hotel.area.area_name %></td>
        </tr>
        <tr>
          <th>価格帯</th>
          <td><%= @hotel.price_range %></td>
        </tr>
        <tr>
          <th>評価(平均)</th>
          <td><%= @hotel.avg_rate %> 点（5点満点）</td>
        </tr>
      </table>
    </div>
  </div>

  <div class="row justify-content-center mt-3">
    <div class="col-10 col-md-auto d-md-flex text-center">
      <%= link_to "レビュー閲覧", admin_hotel_reviews_path(@hotel), class: "col-10 col-md-auto btn btn-primary" %>
      <%= link_to "ホテル情報を編集", edit_admin_hotel_path(@hotel), class: "col-10 col-md-auto btn btn-dark ml-md-2 my-2 my-md-0" %>
    </div>
  </div>
  <div class="row justify-content-end mt-2">
    <%= link_to "ホテル一覧へ戻る", admin_hotels_path, class: "mr-3" %>
  </div>

</div>