config/routes.rb
Rails.application.routes.draw do
  # 会員用deviseのルーティング（/members/sign_in）
  devise_for :members, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  # 管理者用deviseのルーティング（/admin/sign_in）
  devise_for :admin, skip: %i[passwords registrations], controllers: {
    sessions: 'admin/sessions'
  }

  # 管理者用ルーティング
  namespace :admin do
    get '/top' => 'homes#top'
    get 'about' => 'homes#about'

    resources :hotels do
      resources :reviews, except: %i[new create] do # ホテル：レビュー = １：Nだからネスト
        resources :review_comments, only: %i[update destroy] # レビュー：コメント = １：Nだからネスト
      end
    end

    resources :categories, only: %i[index create edit update destroy show]
    resources :areas, only: %i[index create edit update destroy show]
    resources :pictures, only: %i[index new create destroy]

    # 検索機能
    get '/hotel_search' => 'searches#hotel_search'

    # 会員のusernameがURLに表示される
    get '/members' => 'members#index'
    get '/:username' => 'members#show'
    get '/:username/edit' => 'members#edit'
    patch '/:username' => 'members#update'
    patch '/:username/withdraw' => 'members#withdraw', as: 'withdraw_member'
  end

  # 会員側ルーティング
  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get '/privacy' => 'homes#privacy'

    resources :hotels, only: %i[index show] do
      collection do
        get 'ranking'
      end

      resources :reviews do # ホテル：レビュー = １：Nだからネスト
        resources :review_comments, only: %i[create update destroy] # レビュー：コメント = １：Nだからネスト
      end

      resource :favorites, only: %i[create destroy] # ホテル：お気に入り = １：Nだからネスト
    end

    # 検索機能
    get '/hotel_search' => 'searches#hotel_search'

    resources :pictures, only: [:index]

    # お問い合わせ機能
    resources :contacts, only: %i[new create] do
      collection do
        post 'confirm'
        post 'back'
        get 'complete'
      end
    end

    resources :areas, only: [:show]
    resources :categories, only: [:show]

    # URLがusernameになるようにルーティング設定
    get '/mypage' => 'members#mypage', as: "mypage"
    get '/:username' => 'members#show'
    get '/mypage/edit' => 'members#edit', as: "edit_mypage"
    get '/mypage/favorites' => 'members#favorites', as: "favorite_mypage"
    patch '/mypage' => 'members#update', as: "update_mypage"
    get '/mypage/unsubscribe' => 'members#unsubscribe', as: "unsubscribe_member"
    patch '/mypge/withdraw' => 'members#withdraw', as: 'withdraw_member'
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :hotels, dependent: :destroy

  validates :category_name, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @categories = Category.all
    @category = Category.new
  end

  def show
    @categories = Category.all
    @areas = Area.all
    @category = Category.find(params[:id])
    @category_hotel = Hotel.where(category_id: @category.id).page(params[:page]).per(12)
    gon.hotels = Hotel.all
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'カテゴリを登録しました。'
      redirect_to admin_categories_path
    else
      flash.now[:alert] = 'カテゴリを登録できませんでした。再度入力してください。'
      @categories = Category.all
      render :index
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = 'カテゴリを更新しました。'
      redirect_to admin_categories_path
    else
      flash.now[:alert] = 'カテゴリを更新できませんでした。再度入力してください。'
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = 'カテゴリを削除しました。'
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:category_name)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<div class="container-fluid">
  <div class="row justify-content-center mb-3">
    <h3 style="border-bottom: 2px solid #FF9933">カテゴリ編集</h3>
  </div>

  <div class="row justify-content-center">
    <div class="col-md-auto">
    <%= form_with model: @category, url: admin_category_path(@category), local: true do |f| %>
    <table class="table table-borderless">
      <tr>
        <th width="150">カテゴリ名</th>
        <td width="300"><%= f.text_field :category_name, autofocus: true, autocomplete: "category_name", class: "form-control" %></td>
        <td><%= f.submit "変更", class: "btn btn-success" %></td>
      </tr>
    <% end %>
    </table>
    </div>
  </div>

app/views/admin/categories/index.html.erb
<div class="container-fluid">
  <div class="row justify-content-center mb-3">
    <h3 style="border-bottom: 2px solid #FF9933">カテゴリ一覧＆登録</h3>
  </div>

  <%= form_with model: @category, url: admin_categories_path, local: true do |f| %>
  <div class="row justify-content-center mt-5">
    <%= f.label :"カテゴリ名", class: "col-10 offset-1 col-md-2 col-xl-1 font-weight-bold mr-3" %>
    <%= f.text_field :category_name, autofocus: true, autocomplete: "category_name", class: "col-8 col-md-3 form-control" %>
    <%= f.submit "登録", class: "col-6 col-md-auto btn btn-success ml-md-3 mt-3 mt-md-0" %>
  </div>
  <% end %>
  <% if @category.errors.include?(:category_name) %>
    <div  class="col-md-3 offset-md-5 mt-2" style="color: red;"><%= @category.errors.full_messages_for(:category_name).first %></div>
  <% end %>

  <div class="row justify-content-center mt-5">
    <div class="col-md-9 col-lg-7 offset-md-1">

      <table class="table table-bordered table-striped">
        <tr>
          <th width="75%" style="background-color: #99FFCC">カテゴリ名</th>
          <td width="25%" style="background-color: #99FFCC"></td>
        </tr>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.category_name %></td>
          <td class="text-center">
            <%= link_to "編集", edit_admin_category_path(category), class: "btn btn-primary small btn-sm" %>
            <%= link_to "削除", admin_category_path(category), method: :delete, data: { confirm: "カテゴリを削除してよろしいですか?" }, class: "btn btn-danger btn-sm ml-lg-1 mt-1 mt-lg-0" %>
          </td>
        </tr>
      <% end %>
      </table>

    </div>
  </div>

app/views/admin/categories/show.html.erb
<div class="container-fluid">
  <div class="row justify-content-center mb-3">
    <h3 style="border-bottom: 2px solid #FF9933"><%= @category.category_name %>の一覧</h3>
  </div>

  <div class="row justify-content-center">
    <div class="col-md-3 d-flex flex-column">
      <div>
        <%= render "admin/hotels/category_search", categories: @categories %>
      </div>
      <div class="mt-3">
        <%= render "admin/hotels/area_search", areas: @areas %>
      </div>
      <div class="mt-3" id="admin-map-index"></div>
        <script async defer src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV["GOOGLE_MAP_API_KEY"] %>&callback=admin_map_index"></script>
    </div>

    <div class="col-md-9">
      <div class="d-flex flex-wrap">
        <% @category_hotel.includes(:area, :category).each do |hotel| %>
        <div class="d-flex flex-column mb-3 mr-md-2 mr-lg-3">
          <div>
            <%= link_to admin_hotel_path(hotel) do %>
              <% hotel.hotel_images.first(1).each do |image| %>
                <%= attachment_image_tag image, :image, :fill, 225, 200 %>
              <% end %>
            <% end %>
          </div>
          <div style="font-size: 13px; width:225px"><strong><%= hotel.hotel_name %></strong></div>
          <div style="font-size: 11px; width:225px">カテゴリ：<%= hotel.category.category_name %></div>
          <div style="font-size: 11px; width:225px">エリア：<%= hotel.area.area_name %></div>
          <div style="font-size: 11px">評価：<%= hotel.avg_rate %> 点（5点満点）</div>
        </div>
        <% end %>
      </div>
      <div class="d-flex justify-content-center mt-2"><%= paginate @category_hotel %></div>
    </div>

  </div>
</div>