config/routes.rb
Rails.application.routes.draw do
  # 会員用deviseのルーティング（/members/sign_in）
  devise_for :members, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  # 管理者用deviseのルーティング（/admin/sign_in）
  devise_for :admin, skip: %i[passwords registrations], controllers: {
    sessions: 'admin/sessions'
  }

  # 管理者用ルーティング
  namespace :admin do
    get '/top' => 'homes#top'
    get 'about' => 'homes#about'

    resources :hotels do
      resources :reviews, except: %i[new create] do # ホテル：レビュー = １：Nだからネスト
        resources :review_comments, only: %i[update destroy] # レビュー：コメント = １：Nだからネスト
      end
    end

    resources :categories, only: %i[index create edit update destroy show]
    resources :areas, only: %i[index create edit update destroy show]
    resources :pictures, only: %i[index new create destroy]

    # 検索機能
    get '/hotel_search' => 'searches#hotel_search'

    # 会員のusernameがURLに表示される
    get '/members' => 'members#index'
    get '/:username' => 'members#show'
    get '/:username/edit' => 'members#edit'
    patch '/:username' => 'members#update'
    patch '/:username/withdraw' => 'members#withdraw', as: 'withdraw_member'
  end

  # 会員側ルーティング
  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get '/privacy' => 'homes#privacy'

    resources :hotels, only: %i[index show] do
      collection do
        get 'ranking'
      end

      resources :reviews do # ホテル：レビュー = １：Nだからネスト
        resources :review_comments, only: %i[create update destroy] # レビュー：コメント = １：Nだからネスト
      end

      resource :favorites, only: %i[create destroy] # ホテル：お気に入り = １：Nだからネスト
    end

    # 検索機能
    get '/hotel_search' => 'searches#hotel_search'

    resources :pictures, only: [:index]

    # お問い合わせ機能
    resources :contacts, only: %i[new create] do
      collection do
        post 'confirm'
        post 'back'
        get 'complete'
      end
    end

    resources :areas, only: [:show]
    resources :categories, only: [:show]

    # URLがusernameになるようにルーティング設定
    get '/mypage' => 'members#mypage', as: "mypage"
    get '/:username' => 'members#show'
    get '/mypage/edit' => 'members#edit', as: "edit_mypage"
    get '/mypage/favorites' => 'members#favorites', as: "favorite_mypage"
    patch '/mypage' => 'members#update', as: "update_mypage"
    get '/mypage/unsubscribe' => 'members#unsubscribe', as: "unsubscribe_member"
    patch '/mypge/withdraw' => 'members#withdraw', as: 'withdraw_member'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :hotels, dependent: :destroy

  validates :area_name, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :hotels, dependent: :destroy

  validates :category_name, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :message, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :hotel
  belongs_to :member
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  # 住所から緯度経度取得
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :hotel_images, dependent: :destroy
  accepts_attachments_for :hotel_images, attachment: :image # refileで画像複数枚アップロード
  belongs_to :category
  belongs_to :area

  validates :category_id, presence: true
  validates :area_id, presence: true
  validates :hotel_name, presence: true
  validates :price_range, presence: true
  validates :caption, presence: true
  validates :website, presence: true
  validates :address, presence: true
  validates :hotel_images, presence: true

  # 評価の平均点
  def avg_rate
    if reviews.includes(:reviews).empty?
      0.0
    else
      reviews.average(:rate).round(1)
    end
  end

  # ホテル名から検索
  def self.search(search)
    if search
      Hotel.where('hotel_name LIKE(?)', "%#{search}%")
    else
      Hotel.all
    end
  end
end

app/models/hotel_image.rb
class HotelImage < ApplicationRecord
  belongs_to :hotel
  attachment :image, type: :image

  validates :image, presence: true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :review_comments, dependent: :destroy

  validates :username, presence: true, uniqueness: true, length: { minimum: 3, maximum: 10 }
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ } # 全角カタカナ
  validates :first_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :phone_number, presence: true, format: { with: /\A\d{10,11}\z/ }  # 電話番号ハイフンなし10or11桁

  attachment :profile_image, type: :image

  def full_name
    last_name + first_name
  end
end

app/models/picture.rb
class Picture < ApplicationRecord
  attachment :image, type: :image

  validates :image, presence: true
  validates :image_name, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :hotel
  belongs_to :member

  has_many :review_comments, dependent: :destroy

  attachment :review_image, type: :image

  validates :title, presence: true
  validates :rate, presence: true
end

app/models/review_comment.rb
class ReviewComment < ApplicationRecord
  belongs_to :review
  belongs_to :member

  validates :comment, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/areas_helper.rb
module Admin::AreasHelper
end

app/helpers/admin/hotels_helper.rb
module Admin::HotelsHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/pictures_helper.rb
module Admin::PicturesHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  require 'uri'

  def text_url_to_link(text)
    URI.extract(text, %w[http https]).uniq.each do |url|
      sub_text = ''
      sub_text << '<a href=' << url << ' target="_blank">' << url << '</a>'

      text.gsub!(url, sub_text)
    end

    text
  end
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_area_search.html.erb
<div class="border border-info p-1 text-center">
  <h6>エリア検索</h6>
</div>

<div class="border border-info p-3">
  <ul class="list-unstyled">
    <% areas.each do |area| %>
      <%= link_to area_path(area) do %>
        <li style="font-size: 12px"><%= area.area_name %></li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/layouts/_category_search.html.erb
<div class="border border-info p-1 text-center">
  <h6>ジャンル検索</h6>
</div>

<div class="border border-info p-3">
  <ul class="list-unstyled">
    <% categories.each do |category| %>
    <li style="font-size: 12px">
      <%= link_to category_path(category) do %>
        <%= category.category_name %>
      <% end %>
    </li>
    <% end %>
  </ul>
</div>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="notification text-info">
    <p class="alert alert-success"><%= notice %></p>
  </div>
<% end %>
<% if flash.now[:alert] %>
  <div class="notification text-danger">
    <p class="alert alert-danger"><%= alert %></p>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container-fluid">

  <div class="row justify-content-center pt-2">
    <p class="text-center">Copyright Urayasu Hotel Search. <span class="footer-text">All rights reserved.</span></p>
  </div>

  <div class="row justify-content-center">
    <div class="col-lg-2 text-center">
      <%= link_to "プライバシーポリシー", privacy_path, class: "small" %>
    </div>
    <div class="col-lg-2 text-center">
      <%= link_to "お問い合わせ", new_contact_path, class: "small" %>
    </div>
  </div>

</div>

app/views/layouts/_header.html.erb
<div class="container-fluid">
  <nav class="navbar navbar-expand-lg">

      <div class="col-2 col-md-3 flex-column flex-md-row sns-icon">
        <%= link_to "https://www.facebook.com/" do %>
          <i class="fab fa-facebook-square fa-2x ml-md-3"></i>
        <% end %>
        <%= link_to "https://www.twitter.com/" do %>
          <i class="fab fa-twitter-square fa-2x ml-md-3"></i>
        <% end %>
        <%= link_to "https://www.instagram.com/" do %>
          <i class="fab fa-instagram-square fa-2x ml-md-3"></i>
        <% end %>
      </div>

      <div class="col-8 col-md-6 d-flex flex-column">
        <div class="text-center">
          <a class="logo" href="/">
            <%= image_tag 'uhs_logo.png', :size => "150x60", class: "img-fluid" %>
          </a>
        </div>
        <div class="collapse navbar-collapse justify-content-center" id="navbarNavDropdown">
          <ul class="nav nav-tabs navbar-nav mt-2">
          <!--会員がログインした場合-->
          <% if member_signed_in? %>
            <li class="nav-items search-form"><%= render "public/searches/search" %></li>
            <li class="nav-items"><%= link_to "マイページ", mypage_path, class: "nav-link active text-center" %></li>
            <li class="nav-items"><%= link_to "ホテル", hotels_path, class: "nav-link active text-center" %></li>
            <li class="nav-items"><%= link_to "ランキング", ranking_hotels_path, class: "nav-link active text-center" %></li>
            <li class="nav-items"><%= link_to "ギャラリー", pictures_path, class: "nav-link active text-center" %></li>
            <li class="nav-items"><%= link_to "ログアウト", destroy_member_session_path, method: :delete, class: "nav-link active text-center" %></li>
          <!--管理者がログインした場合-->
          <% elsif admin_signed_in? %>
            <li class="nav-items search-form"><%= render "admin/searches/search" %></li>
            <li class="nav-items"><%= link_to "ホテル", admin_hotels_path, class: "nav-link active text-center" %></li>
            <li class="nav-items"><%= link_to "カテゴリ", admin_categories_path, class: "nav-link active text-center" %></li>
            <li class="nav-items"><%= link_to "エリア", admin_areas_path, class: "nav-link active text-center" %></li>
            <li class="nav-items"><%= link_to "メンバー", admin_members_path, class: "nav-link active text-center" %></li>
            <li class="nav-items"><%= link_to "ギャラリー", admin_pictures_path, class: "nav-link active text-center" %></li>
            <li class="nav-items"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link active text-center" %></li>
          <!--ログインしていない場合-->
          <% else %>
            <li class="nav-items search-form"><%= render "public/searches/search" %></li>
            <li class="nav-items"><%= link_to "トップ", root_path, class: "nav-link active text-center" %></li>
            <li class="nav-items"><%= link_to "アバウト", about_path, class: "nav-link active text-center" %></li>
            <li class="nav-items"><%= link_to "サインアップ", new_member_registration_path, class: "nav-link active text-center" %></li>
            <li class="nav-items"><%= link_to "ログイン", new_member_session_path, class: "nav-link active text-center" %></li>
          <% end %>
          </ul>

        </div>
      </div>

      <div class="col-2 col-md-3 text-center">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="search">
          <% if admin_signed_in? %>
            <%= render "admin/searches/search" %>
          <% else %>
            <%= render "public/searches/search" %>
          <% end %>
        </div>
      </div>

  </nav>
</div>

app/views/layouts/_hotel.html.erb
<div class="mt-2">
<% hotel.hotel_images.first(1).each do |image| %>
  <%= attachment_image_tag image, :image, class: "hotel-first-image" %>
<% end %>
</div>
<table class="table table-bordered table-sm text-left mt-2" style="font-size: 9px">
  <tr>
    <th>ホームページ</th>
    <td class="text-break"><%= text_url_to_link(h(hotel.website)).html_safe %></td>
  </tr>
  <tr>
    <th>カテゴリ</th>
    <td><%= hotel.category.category_name %></td>
  </tr>
  <tr>
    <th>エリア</th>
    <td><%= hotel.area.area_name %></td>
  </tr>
  <tr>
    <th>価格帯</th>
    <td><%= hotel.price_range %></td>
  </tr>
  <tr>
    <th>評価(平均)</th>
    <td><%= hotel.avg_rate %> 点（5点満点）</td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>浦安ホテルサーチ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= include_gon(init: true) %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/css/lightbox.css" rel="stylesheet">

  </head>

  <body id="content">

    <header>
      <%= render "layouts/header" %>
    </header>

    <div id="flash-message">
      <%= render "layouts/flash" %>
    </div>

    <main>
      <%= yield %>
    </main>

    <footer>
      <%= render "layouts/footer" %>
    </footer>

    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/js/lightbox.min.js" type="text/javascript"></script>
  </body>
</html>